version: "3"
services:

  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/html
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:5.5-fpm
    ports:
      - "9000:9000"
    volumes:
     - ./html:/html
  mysql:
     image: mysql:5.7
     ports:
      - "3306:3306"
     environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    links:
       - mysql